### PR TITLE
Redesign

### PR DESCRIPTION
**Pull request by terracomma**

### CODE REVIEW

**Comment by vabarbosa** [comment]
@terracomma, playing around with the new ui (looks great). however, when checkboxes are clicked the checkmark is not displayed (both in FF and IE, appears fine in Chrome)

**Comment by terracomma** [comment]
Hmm, @vabarbosa - That's probably an encoding error in the way I've got the SVG in CSS. I'll look into it.

Thanks!

**Comment by vabarbosa** [comment]
@terracomma, are there styles for disabled buttons?

**Comment by vabarbosa** [comment]
similar to the checkbox SVG, the select (dropdown) arrow is not displayed cross browser

**Comment by terracomma** [comment]
Most recent push should solve the problem with the checkbox and select chevron. Could you pull and verify for me @vabarbosa?

**Pull request merged**
